name: 'container'
description: 'An action to create a container and push it to git'

inputs:
  docker_repo:
    required: true
  secret:
    description: 'git secret'
    required: true
  actor:
    description: 'git username'
    required: true
runs:
  using: "composite"
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: https://${{ inputs.docker_repo }}
        username: ${{ inputs.actor }}
        password: ${{ inputs.secret }}
    - uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: 
          ${{ inputs.docker_repo }}/tuto_dev_lylia:latest, 
          ${{ inputs.docker_repo }}/tuto_dev_lylia:${{ github.ref_name }}
