name: Check sources
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check script
        run: test -e run.sh
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v2
      - name : run shellcheck
        uses: ludeeus/action-shellcheck@master
  tests:
    needs: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v2
      - name : run tests
        run: make tests
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make doc
        run: make doc
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
