name: Check sources
on:
  push
jobs:
  deploy:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check script
        run: test -e run.sh
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v2
      - name : run shellcheck
        uses: ludeeus/action-shellcheck@master
  tests:
    if: github.ref_name != 'main'
    needs: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v2
      - name : run tests
        run: make tests
  # doc:  
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: make doc
  #     - name: Deploy
  #       uses: crazy-max/ghaction-github-pages@v2
  #       with:
  #         build_dir: ./dist
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  container:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v2
      - uses: ./.github/actions/container
        with:
          secret : ${{ secrets.GITHUB_TOKEN }}
          actor : ${{ github.actor }}
      
    #   - uses:  actions/checkout@v2
    #   - name: Log in to the Container registry
    #     uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
    #     with:
    #       registry: https://ghcr.io
    #       username: ${{ github.actor }}
    #       password: ${{ secrets.GITHUB_TOKEN }}
    #   - uses: docker/build-push-action@v2
    #     with:
    #       context: .
    #       push: true
    #       tags: 
    #         ghcr.io/lyliaz/tuto_test:latest, ghcr.io/lyliaz/tuto_test:${{ github.ref_name }}
