name: Check sources
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check script
        run: test -e run.sh
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v2
      - name : run shellcheck
        uses: ludeeus/action-shellcheck@master
  tests:
    needs: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v2
      - name : run tests
        run: make tests
  # doc:  
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: make doc
  #     - name: Deploy
  #       uses: crazy-max/ghaction-github-pages@v2
  #       with:
  #         build_dir: ./dist
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  container:
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v2
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/tuto_test_1:latest
