name: Check sources
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check script
        run: test -e run.sh
      - name: run tests
        run: make tests
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v2
      - name : run shellcheck
        uses: ludeeus/action-shellcheck@master
